name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2



      - name: Build Docker image
        run: |
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiktok-backend/tiktok-backend:$GITHUB_SHA \
                         -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiktok-backend/tiktok-backend:latest .

      - name: Push Docker image
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiktok-backend/tiktok-backend:$GITHUB_SHA
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tiktok-backend/tiktok-backend:latest

      - name: Deploy to GCE VM
        run: |
          gcloud compute ssh ${{ secrets.GCE_INSTANCE_NAME }} --zone=${{ secrets.GCE_ZONE }} --command "\
            echo '${{ secrets.ENV_FILE }}' > /tmp/tiktok.env && \
            chmod 600 /tmp/tiktok.env && \
            gcloud auth configure-docker us-west1-docker.pkg.dev && \
            docker network create tiktok-net || true && \
            docker rm -f mongodb || true && \
            docker run -d --name mongodb --network tiktok-net -p 27017:27017 -v mongo_data:/data/db -e MONGO_INITDB_DATABASE=tiktok_clone mongo:latest && \
            docker rm -f tiktok-backend || true && \
            echo '${{ secrets.ENV_FILE }}' > /tmp/tiktok.env && \
            chmod 600 /tmp/tiktok.env && \
            docker run -d --name tiktok-backend --network tiktok-net -p 5000:5000 --env-file /tmp/tiktok.env us-west1-docker.pkg.dev/prime-hologram-467111-s4/tiktok-backend/tiktok-backend:latest
          "
